package io.github.bilcitytycoon;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.utils.Json;
import com.badlogic.gdx.utils.JsonValue;

public class Faculty extends Building implements Json.Serializable{

    private static final String UPGRADE_TYPE1 ="Ventilation";
    private static final String UPGRADE_TYPE2 ="Energy Efficiency";
    private static final String UPGRADE_TYPE3 ="Capacity";
    public double income; //Income generated by the faculty
    public transient Image image; //Visual representation of the faculty
    public String imagePath;
    public String info; //Additional information about the faculty
    public int buildTime; //Time required to build the faculty
    protected Upgrade[] upgrades; // Array to hold multiple upgrades
    protected int currentUpgradeLevel;//tracks the current upgrade

    public Faculty(String name, int cost, int bill, int income, String imagePath, int buildTime, String info,int studentSatisfactionPoint,int universityReputationPoint) {
        super(name, cost, bill,studentSatisfactionPoint,universityReputationPoint);

        this.income = income;
        this.info = info;
        this.buildTime = buildTime;
        this.imagePath = imagePath;
        this.upgrades = new Upgrade[3]; // Initialize the upgrades array with a size of 3
        this.currentUpgradeLevel = 0; // Tracks the current level of upgrade


        //Load the image for the faculty, with validation
        if (imagePath == null || imagePath.isEmpty()) {
            throw new IllegalArgumentException("Image path cannot be null or empty");
        }

        if (Gdx.files.internal(imagePath).exists()) {
            this.image = new Image(new Texture(Gdx.files.internal(imagePath)));
        } else {
            throw new IllegalArgumentException("Image file not found: " + imagePath);
        }
    }

    public Faculty(){
        super("Faculty", 100, 100, 0, 0);
    }

    //Getter methods for the faculty's properties
    public double getBuildCost() {
        return this.buildCost;
    }



    @Override
    public Image getImage() {
        if (image == null && imagePath != null && Gdx.files.internal(imagePath).exists()) {
            image = new Image(new Texture(Gdx.files.internal(imagePath)));
        }
        return image;
    }
    public String getImagePath(){
        return this.imagePath;
    }
    public int getBuildTime(){
        return this.buildTime;
    }

    @Override
    public String getInfo() {
        return this.info;
    }
     // Override toString for a detailed representation
     @Override
     public String toString() {
         return "Faculty{name='" + name + "', cost=" + buildCost + ", bill=" + bill +
                ", income=" + income + ", buildTime=" + buildTime + "}";
     }

    public void addUpgrade(Upgrade upgrade, int level){
        if (level < 1 || level > upgrades.length) {
            throw new IllegalArgumentException("Invalid upgrade level: " + level);
        }
        upgrades[level - 1] = upgrade;
    }

    public Upgrade[] getUpgrades() {
        return upgrades;
    }

    public int getCurrentUpgradeLevel() {
        return currentUpgradeLevel;
    }

    // Apply the next upgrade level
    public void applyNextUpgrade(String info,BilCityTycoonGame game, MoneyHandler moneyHandler, Player player) {
        if (currentUpgradeLevel < upgrades.length && upgrades[currentUpgradeLevel] != null) {
            Upgrade upgrade = upgrades[currentUpgradeLevel];
            upgrade.applyUpgrade(moneyHandler, player); // Mark the upgrade as applied
            applyUpgradeEffects(upgrade, info, game, moneyHandler, player); // Apply the effects of the upgrade
            currentUpgradeLevel++; // Move to the next upgrade level
        } else {
            System.out.println("No more upgrades available or upgrade not defined for this level.");
        }
    }

    // Apply the effects of the upgrade to the building
    private void applyUpgradeEffects(Upgrade upgrade, String info,BilCityTycoonGame game, MoneyHandler moneyHandler, Player player) {
        if (upgrade != null) {
            upgrade.applyUpgrade(moneyHandler, player);
            }
            this.info += "\n " + info + upgrade.getName();
    }
    @Override
    public void write(Json json) {
        json.writeValue("type", this.getClass().getName());
        json.writeValue("name", name);
        json.writeValue("buildCost", buildCost);
        json.writeValue("bill", bill);
        json.writeValue("studentSatisfactionPoint", studentSatisfactionPoint);
        json.writeValue("universityReputationPoint", universityReputationPoint);
        json.writeValue("income", income);
        json.writeValue("imagePath", imagePath);
        json.writeValue("info", info);
        json.writeValue("buildTime", buildTime);
        json.writeValue("currentUpgradeLevel", currentUpgradeLevel);
        json.writeValue("upgrades", upgrades);
    }


    @Override
    public void read(Json json, JsonValue jsonData) {
        this.name = jsonData.getString("name");
        this.buildCost = jsonData.getInt("buildCost");
        this.bill = jsonData.getInt("bill");
        this.studentSatisfactionPoint = jsonData.getInt("studentSatisfactionPoint");
        this.universityReputationPoint = jsonData.getInt("universityReputationPoint");
        this.income = jsonData.getInt("income");
        this.imagePath = jsonData.getString("imagePath");
        this.info = jsonData.getString("info");
        this.buildTime = jsonData.getInt("buildTime");
        this.currentUpgradeLevel = jsonData.getInt("currentUpgradeLevel", 0);
        if (imagePath != null && Gdx.files.internal(imagePath).exists()) {
            this.image = new Image(new Texture(Gdx.files.internal(imagePath)));
        }

        Upgrade[] loadedUpgrades = json.readValue(Upgrade[].class, jsonData.get("upgrades"));
        this.upgrades = loadedUpgrades != null ? loadedUpgrades : new Upgrade[3]; // null check
    }



}

